map/urls.py
from django.urls import path
from map.views import index
app_name = 'map'
urlpatterns = [
	path('map_index/', index,name='map_index'),
]

mlearnapp/urls.py
from django.urls import path
from mlearnapp.views import mindex,fitp,modelList,getFileHeader,getFeatures
app_name = 'mlearnapp'
urlpatterns = [
	path('mindex/', mindex,name='mindex'),
	path('modelList/', modelList,name='modelList'),
	path('fitp/',fitp,name='fitp'),
    path('getFileHeader',getFileHeader,name="getFileHeader"),
    path('getFeatures',getFeatures,name="getFeatures")
]

xwproj/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

mlearnapp/views.py
from django.shortcuts import render
from django.http import JsonResponse,HttpResponse
import pandas as pd

from featureFunctions import stepwise_selection
# Create your views here.
def mindex(request):
    data = dict()
    data["featureSelect"] = {
        "sklearn.decomposition-PCA":"主成分分析法",
        "sklearn.discriminant_analysis-LinearDiscriminantAnalysis":"线性判别分析法",
        "self_P":"逐步回归降维法(P值)"
    }
    return render(request,"mlearnapp/index.html" ,data)

def modelList(request):
    mType = request.GET.get("modelType")
    data = {
        "分类":{
            "sklearn.linear_model-LogisticRegression":"逻辑斯遆回归",
            "sklearn.svm-SVC":"支持向量机",
            "sklearn.tree-DecisionTreeClassifier":"决策树",
            "sklearn.ensemble-RandomForestClassifier":"随机森林分类",
            "sklearn.neighbors-KNeighborsClassifier":"KNN",
            "sklearn.discriminant_analysis-LinearDiscriminantAnalysis":"fisher判别",
        },
        "回归":{
            "sklearn.linear_model-LinearRegression":"简单线性回归",
        }
    }
    return JsonResponse({"modelList":data[mType]});

def fitp(request):
    from sklearn.model_selection import train_test_split
    pd_excel = pd.read_excel(request.FILES.get('train_test_file'))
    featureSelectMethod = request.POST.get("featureSelect")
    modelSelectMethod = request.POST.get("modelSelect")
    y = pd_excel["y"]
    myfeatures = request.POST.get("mfeatures").split(",")
    X = pd_excel[myfeatures]
    train_X,test_X, train_y, test_y  = train_test_split(X,y,test_size = 0.3)
    mfunc = getReflectFunc(modelSelectMethod)
    clf = mfunc().fit(train_X,train_y)
    y_pred = clf.predict(test_X)
    err_no = (test_y!=y_pred).sum()
    if len(y.unique().tolist())>2:
        message = "样本总数： %d，误差率：%d%%" % (test_X.shape[0],(100*abs(test_y.sum()-y_pred.sum())/test_y.sum()))
    else:
        message = "样本总数： %d 错误样本数 : %d，正确率：%d%%" % (test_X.shape[0],err_no,(100*(test_X.shape[0]-err_no)/test_X.shape[0]))
    return HttpResponse(message+str(test_y.tolist())+str(y_pred.tolist()))

def getFileHeader(request):
    mFile_pd = pd.read_excel(request.FILES.get("train_test_file"));
    html = "<table class='table'>"
    content = ""
    for cl in mFile_pd.columns:
        content += f"<tr><td>{cl}</td><td><select name='cl_{cl}'><option value='1'>原值</option><option value='2'>不参与训练</option><option value='3'>归一化</option><option value='4'>标准化</option><option value='5'>独热编码</option>><option value='6'>预测值</option></select></td></tr>"
    html+=content+"</table>"
    return HttpResponse(html)

def getFeatures(request):
    mFile_pd = pd.read_excel(request.FILES.get("train_test_file"))
    y = mFile_pd['y']
    X = mFile_pd.drop(['y'],axis=1)
    fsMethod = request.POST.get("featureSelect")
    if "self" in fsMethod:
        columns = stepwise_selection(X,y)
    elif fsMethod=="":
        columns = X.columns
    elif "PCA" in fsMethod or "LinearDiscriminantAnalysis" in fsMethod:
        fsclass = getReflectFunc(fsMethod)
        columns = fsclass(2).fit_transform(X).columns
    else:
        raise Exception("选择特征异常")
    return HttpResponse(",".join(columns))

def getReflectFunc(st):
    oriM = st.split(".")[0]
    ms,cs = st.split("-")
    m = __import__(ms,fromlist=(oriM,))
    c = getattr(m,cs)
    return c

templates/mlearnapp/index.html
{% extends "base.html" %}
{% block title %}守正评级数据仓库{% endblock %}
{% block content %}
<div class="row">
<div class="col-md-2"></div>
<div class="col-md-8">
    <form action="{% url 'mlearnapp:fitp' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-group">
          <label for="exampleInputFile">请上传训练测试集</label>
          <input type="file" id="exampleInputFile" name = "train_test_file" onchange="showFileHeader(this)">
          <p class="help-block">Example block-level help text here.</p>
      </div>
      <div class="form-group" id = "columns"></div>
      <div class ="form-group">
          <label>特征选择</label>
          <select id = "featureSelect" name="featureSelect" onChange="changeFeature()">
            <option value=''>请选择</option>
            <option value=''>不启用特征选择</option>
            {% for f,desc in featureSelect.items %}
                <option value='{{ f }}'>{{ desc }}</option>
            {% endfor %}
          </select>
      </div>
      <div class="form-group">
            <label id = "featureLabel" style="display:none">已选择的特征</label>
            <textarea type="text" name = "mfeatures" style="display:none"></textarea>
      </div>
      <div class ="form-group">
          <label>模型类型选择</label>
          <select id= "modelType" onChange="changeModel()">
            <option value="">请选择模型类型</option>
            <option value="分类">分类问题</option>
            <option value="回归">回归问题</option>
          </select>
          <label>模型选择</label>
          <select id="modelSelect" name = "modelSelect">

          </select>
      </div>

      <button type="submit" class="btn btn-default">训练模型</button>
   </form>
</div>
<div class="col-md-2"></div>
</div>
<script language="JavaScript">
    function changeModel(){
        var mType = document.getElementById("modelType");
        var val = mType.value;
        if (val==""){
            alert("必须选择模型类型");
            return;
        }
        var mSelect = document.getElementById("modelSelect");
        var xmlHttp = new XMLHttpRequest();
        xmlHttp.onreadystatechange = function()
        {
            if (xmlHttp.readyState == 4 && xmlHttp.status == 200) {
                var data = JSON.parse(xmlHttp.responseText);
                for (var k in data.modelList){
                    mSelect.options[mSelect.options.length] = new Option(data.modelList[k],k);
                }
            }
        }
        xmlHttp.open("GET", "{% url 'mlearnapp:modelList' %}?modelType="+val, false);
        xmlHttp.send();
    }

    function changeFeature(){
        var form = new FormData();
        var mFile = document.getElementsByName("train_test_file")[0];
        var mType = document.getElementById("featureSelect");
        var val = mType.value;
        var myfeatures = document.getElementsByName("mfeatures")[0];
        var featureLabel = document.getElementById("featureLabel");
        form.append("csrfmiddlewaretoken",'{{ csrf_token }}');
        form.append("train_test_file",mFile.files[0])
        form.append("featureSelect",val);
        var xmlHttp = new XMLHttpRequest();
        xmlHttp.onreadystatechange = function()
        {
            if (xmlHttp.readyState == 4 && xmlHttp.status == 200) {
                var data = xmlHttp.responseText;
                featureLabel.style.display = "block";
                myfeatures.style.display="block";
                myfeatures.value = data;
                
            }
        }
        xmlHttp.open("POST", "{% url 'mlearnapp:getFeatures' %}", false);
        xmlHttp.send(form);
    }

    function insertAfter( newElement, targetElement ){ 
        var parent = targetElement.parentNode; // 找到指定元素的父节点 
        if( parent.lastChild == targetElement ){
            parent.appendChild( newElement, targetElement ); 
        }else{ 
            parent.insertBefore( newElement, targetElement.nextSibling ); 
        } 
    }

    function showFileHeader(){
        if(confirm("确认上传的excel有header？"))
        var mFile = document.getElementsByName("train_test_file")[0];
        if (mFile.files.length<=0){
            alert("未上传文件");
            return;
        }
        var form = new FormData();
        form.append('train_test_file',mFile.files[0]);
        form.append("csrfmiddlewaretoken",'{{ csrf_token }}');
        var xmlHttp = new XMLHttpRequest();
        xmlHttp.onreadystatechange = function()
        {
            if (xmlHttp.readyState == 4 && xmlHttp.status == 200) {
                document.getElementById("columns").innerHTML= "";
                var data = xmlHttp.responseText;
                document.getElementById("columns").innerHTML= data;
            }
        }
        xmlHttp.open("POST", "{% url 'mlearnapp:getFileHeader' %}", true);
        xmlHttp.send(form);

    }
</script>
{% endblock %}