article/urls.py
from django.urls import path
from article.views import aindex,detail,setRate,search,doExcelIndex,getNews
app_name = 'article'
urlpatterns = [
	path('aindex/', aindex,name='aindex'),
    path('detail/', detail,name="detail"),
    path('setRate/', setRate,name="setRate"),
    path('search/', search,name="search"),
    path('doExcelIndex/',doExcelIndex, name= "doExcelIndex"),
    path('getNews/',getNews,name = "getNews")
]

firstapp/urls.py
from django.urls import path
from firstapp.views import index,myprofile,search,data_index,getExcelSample,checkExcelSample,getDataSet,getDataSetByName
app_name = 'firstapp'
urlpatterns = [
	path('myprofile/', myprofile,name='myprofile'),
	path('search/',search,name='search'),
    path("data_index/",data_index,name='data_index'),
    path("getExcelSample/",getExcelSample,name='getExcelSample'),
    path("checkExcelSample/",checkExcelSample,name="checkExcelSample"),
    path("getDataSet/",getDataSet,name = "getDataSet"),
    path("getDataSetByName/",getDataSetByName,name = "getDataSetByName"),
]

map/urls.py
from django.urls import path
from map.views import index
app_name = 'map'
urlpatterns = [
	path('map_index/', index,name='map_index'),
]

mlearnapp/urls.py
from django.urls import path
from mlearnapp.views import mindex,fitp,modelList,getFileHeader,getFeatures
app_name = 'mlearnapp'
urlpatterns = [
	path('mindex/', mindex,name='mindex'),
	path('modelList/', modelList,name='modelList'),
	path('fitp/',fitp,name='fitp'),
    path('getFileHeader',getFileHeader,name="getFileHeader"),
    path('getFeatures',getFeatures,name="getFeatures")
]

xwproj/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

templates/base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{% block title %}{% endblock %}</title>
<script src="https://unpkg.com/vue/dist/vue.js"></script>
<!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- 可选的 Bootstrap 主题文件（一般不用引入） -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">首页 <span class="sr-only">(current)</span></a></li>
        <li><a href="{% url 'home' %}">首页</a></li>
        <li><a href="http://39.97.184.89:8888/" target='blank'>jupyter工具</a></li>
        <li><a href="http://39.97.184.89:8000/#/home">爬虫中心</a></li>
        <li><a href="{% url 'mlearnapp:mindex' %}">自助建模</a></li>
        <li><a href="{% url 'firstapp:data_index' %}">取数中心</a></li>
        <li><a href="{% url 'article:aindex' %}">文章情感分类</a></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"     aria-expanded="false">Dropdown <span class="caret"></span></a>
                 <ul class="dropdown-menu">
                    <li><a href="#">Java</a></li>
                    <li><a href="#">Python</a></li>
                    <li><a href="#">C#</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">One more separated link</a></li>
                </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" action = "{% url 'firstapp:search' %}" method='post'>
	{% csrf_token %}
        <div class="form-group">
          <input type="text" name="main_key" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

{% block content %}

{% endblock %}

<div id="app" class="content" style="display:none">
  {% verbatim myblock %}
  <p>{{ message }}</p>
  {% endverbatim myblock %}
</div>

<script>
new Vue({
  el: '#app',
  data: {
    message: '这是徐威的个人主页，demo用'
  }
})
</script>
</body>

templates/crawl_index.html
{% extends "base.html" %}
{% block title %}守正评级数据仓库{% endblock %}
{% block content %}
<div style="margin-left:15%;margin-right:15%">
<table class = "table">
    {% for head in headers %}
	    <th>{{ head }}</th>
    {% endfor %}
    <th>操作</th>
    {% for line in data %}
        <tr>
            {% for td in line %}
                <td>{{td}}</td>
            {% endfor %}
            <td><button type="button" class="btn btn-default" onclick="doSpider('{{ line.0 }}','{{ line.1 }}','{{ line.2 }}')">执行</button></td>
        </tr>
    {% endfor %}
</table>
<script type="text/javascript">
    function doSpider(m,c,f){
        if(window.XMLHttpRequest)//如果有XMLHttpRequest，那就是非IE6浏览器。()里面加window的原因下面会有描述。
        {
             var oAjax = new XMLHttpRequest();//创建ajax对象
        }
        else//如果没有XMLHttpRequest，那就是IE6浏览器
        {
             var oAjax = new ActiveXObject("Microsoft.XMLHTTP");//IE6浏览器创建ajax对象
        }
        oAjax.open("GET","/crawl/crawl_action?m="+m+"&c="+c+"&f="+f,true);//加上t='+new Date().getTime()"的目的是为了消除缓存，每次的t的值不一样。
        oAjax.send();
        oAjax.onreadystatechange=function()
        {
             //oAjax.readyState  //浏览器和服务器，进行到哪一步了。
             //0->（未初始化）：还没有调用 open() 方法。
             //1->（载入）：已调用 send() 方法，正在发送请求。
             //2->载入完成）：send() 方法完成，已收到全部响应内容。
             //3->（解析）：正在解析响应内容。
             //4->（完成）：响应内容解析完成，可以在客户端调用。
             if(oAjax.readyState==4)
             {
                   if(oAjax.status==200)//判断是否成功,如果是200，就代表成功
                   {
                         alert("成功"+oAjax.responseText);//读取a.txt文件成功就弹出成功。后面加上oAjax.responseText会输出a.txt文本的内容
                   }
                   else
                   {
                         alert("失败");
                   }
             }
         };
    }
</script>
</div>
{% endblock %}

templates/get_data_index.html
{% extends "base.html" %}
{% block title %}守正评级数据仓库{% endblock %}
{% block content %}
<div style="margin-left:15%;margin-right:15%">
    <p> 说明：本页面两个功能，一是添加数据模板，以便方便其他人下载；二是自己提供EXCEL数据模板，按照所需指标填充</p>
    <div class = "row">
        <form action = "{% url 'firstapp:getExcelSample' %}" method="post" id = "getExcelForm" enctype="multipart/form-data">
            {% csrf_token %}
             <div class="form-group">
                <label>获取的报告期</label>
                <input type="text" class="form-control" name="report_period" id = "report_period"/>
                <label for="myExcel">上传EXCEL数据集模板</label>
                <input type="file" id="myExcel" name="myExcel">
                <p class="help-block">Example block-level help text here.</p>
             </div>
      </form>
             <button type="submit" class="btn btn-default" onClick="checkExcelSample()">Submit</button>
    </div><hr/>
    <div class="row" id = "callbackinfo1">
    </div>
    <hr/>
    <div class ="row">
            <div class="form-group">
                <label for="data_name">数据集模板名称:</label>
                <input type="email" class="form-control" id="data_name" name="data_name" placeholder="比如全部发债企业">
                <label for="data_desc">SQL描述:</label>
                <textarea class="form-control" name ="data_desc"></textarea>
                <button type="button" class="btn btn-default" onClick= "checkDataSet()">Submit</button>
            </div>
    </div>
    <hr/>
    <div class="row" id = "dataSets">
        <table class = "table">
        {% for nm in dataSetInfo %} 
            <tr>
                {% for n in nm %}
                    <td><form action = "{% url 'firstapp:getDataSetByName' %}" method="post"> {% csrf_token %} <input type="hidden" class="display:none" name = "data_name" value="{{ n.0 }}"/> <button class = "btn-primary" type="submit">{{ n.0 }}</button></form></td>
                {% endfor %}
            </tr>
        {% endfor %}
        <table>
    </div>
</div>
<script language="javascript">
    function checkExcelSample(){
        var form = new FormData();
        var mFile = document.getElementsByName("myExcel")[0];
        form.append("csrfmiddlewaretoken",'{{ csrf_token }}');
        form.append("myExcel",mFile.files[0]);


        if(window.XMLHttpRequest)//如果有XMLHttpRequest，那就是非IE6浏览器。()里面加window的原因下面会有描述。
        {
            var oAjax = new XMLHttpRequest();//创建ajax对象
        }
        else
        {
            var oAjax = new ActiveXObject("Microsoft.XMLHTTP");//IE6浏览器创建ajax对象
        }

        oAjax.onreadystatechange=function()
        {
            console.log("f0");
            if(oAjax.readyState==4)
            {
                console.log("f1");
                if(oAjax.status==200)//判断是否成功,如果是200，就代表成功
                {
                    document.getElementById("callbackinfo1").innerHTML = oAjax.responseText;
                    if(oAjax.responseText=="OK"){
                        alert("检验无误，接下来下载数据");
                        getExcelData();
                    }
                    else{
                        if (confirm("发现了问题，无视问题继续下载？")){
                            getExcelData();
                        }
                    }
                }
                else
                {
                    alert("失败");
                }
            }
        };
        oAjax.open("POST","{% url 'firstapp:checkExcelSample' %}",false);//加上t='+new Date().getTime()"的目的是为了消除缓存，每次的t的值不一样。
        oAjax.send(form);

    }

    function getExcelData(){
                    var form = document.getElementById("getExcelForm");
                    form.submit();
    }

    function checkDataSet(){
        var form = new FormData();
        form.append("csrfmiddlewaretoken",'{{ csrf_token }}');
        form.append("data_name",document.getElementsByName("data_name")[0].value);
        form.append("data_desc",document.getElementsByName("data_desc")[0].value);

        if(window.XMLHttpRequest)//如果有XMLHttpRequest，那就是非IE6浏览器。()里面加window的原因下面会有描述。
        {
            var oAjax = new XMLHttpRequest();//创建ajax对象
        }
        else
        {
            var oAjax = new ActiveXObject("Microsoft.XMLHTTP");//IE6浏览器创建ajax对象
        }

        oAjax.onreadystatechange=function()
        {
            console.log("f0");
            if(oAjax.readyState==4)
            {
                console.log("f1");
                if(oAjax.status==200)//判断是否成功,如果是200，就代表成功
                {
                    document.getElementById("dataSets").innerHTML = oAjax.responseText;
                }
                else
                {
                    alert("失败");
                }
            }
        };
        oAjax.open("POST","{% url 'firstapp:getDataSet' %}",false);//加上t='+new Date().getTime()"的目的是为了消除缓存，每次的t的值不一样。
        oAjax.send(form);

    }
</script>
{% endblock %}

templates/header.html
<!--模板中声明引入静态文件的标签，只有使用它,static标签才能使用-->
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="https://blog.csdn.net/chengqiuming"><img src="{% static '/images/logo.png' %}" width="100px"></a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="navigation">
                <!--blog是urlpatterns中定义的namespace，blog_title是视图函数-->
                <li><a href="{% url 'blog:blog_title' %}">博客</a></li>
                <!-- 增加文章入口-->
                <li><a href="{% url 'article:article_titles' %}">文章</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right:10px">
                {% if user.is_authenticated %}
                <li>
                    <div class="dropdown" style="margin-top:8px">
                        <button class='btn btn-default dropdown-toggle' type='button' id='dropdownMenu' data-toggle='dropdown'>{{ user.username }}<span class='caret'></span></button>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
                            <li><a href="{% url 'account:my_information' %}">个人信息</a></li>
                            <li><a href="{% url 'article:article_column' %}">后台管理</a></li>
                        </ul>
                    </div>
                </li>
                <li><a href="#">{{ user.username }}</a></li>
                <li><a href="{% url 'account:user_logout' %}">退出</a></li>
                {% else %}
                <li><a href="{% url 'account:user_login' %}">登录</a></li>
                 <!-- 增加注册入口-->
                <li><a href="{% url 'account:user_register' %}">注册</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>
<script src="{% static 'js/jquery.js'%}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>

templates/home.html
{% extends "base.html" %}
{% block title %}守正评级数据仓库{% endblock %}
{% block content %}
<div class = "text-center">
	<h1>欢迎访问守正评级数据中心</h1>
	{% load staticfiles %}
	<!--<img src = "{% static 'python.jpg' %}">-->
	<p>本站点将作为数据库字典，共非sqler了解自己所关心的数据，包括查询，规模，下载，修改</p>
    <a href="{% url 'firstapp:myprofile' %}" download>点击下载PDF</a>
</div>
{% endblock %}

templates/myprofile.html
{% extends 'base.html' %}
{% block content %}
{% pdf %}

{% endblock %}

templates/search.html
{% extends "base.html" %}
{% block title %}守正评级数据仓库{% endblock %}
{% block content %}
<div style="margin-left:15%;margin-right:15%">
{% if table %}
<h2>库信息</h2>
<table class = "table">
    {% for head in table_headers %}
	    <th>{{ head }}</th>
    {% endfor %}
    {% for line in table %}
        <tr>
            {% for td in line %}
                <td>{{td}}</td>
            {% endfor %}
            <!--<td><button type="button" class="btn btn-default" onclick="doSpider('{{ line.0 }}','{{ line.1 }}','{{ line.2 }}')">执行</button></td>-->
        </tr>
    {% endfor %}
</table>
{% endif %}
{% if column %}
<h2>指标信息</h2>
<table class = "table">
    {% for head in column_headers %}
	    <th>{{ head }}</th>
    {% endfor %}
    {% for line in column %}
        <tr>
            {% for td in line %}
                <td>{{td}}</td>
            {% endfor %}
            <!--<td><button type="button" class="btn btn-default" onclick="doSpider('{{ line.0 }}','{{ line.1 }}','{{ line.2 }}')">执行</button></td>-->
        </tr>
    {% endfor %}
</table>
{% endif %}
<script type="text/javascript">
    function doSpider(m,c,f){
        if(window.XMLHttpRequest)//如果有XMLHttpRequest，那就是非IE6浏览器。()里面加window的原因下面会有描述。
        {
             var oAjax = new XMLHttpRequest();//创建ajax对象
        }
        else//如果没有XMLHttpRequest，那就是IE6浏览器
        {
             var oAjax = new ActiveXObject("Microsoft.XMLHTTP");//IE6浏览器创建ajax对象
        }
        oAjax.open("GET","/crawl/crawl_action?m="+m+"&c="+c+"&f="+f,true);//加上t='+new Date().getTime()"的目的是为了消除缓存，每次的t的值不一样。
        oAjax.send();
        oAjax.onreadystatechange=function()
        {
             //oAjax.readyState  //浏览器和服务器，进行到哪一步了。
             //0->（未初始化）：还没有调用 open() 方法。
             //1->（载入）：已调用 send() 方法，正在发送请求。
             //2->载入完成）：send() 方法完成，已收到全部响应内容。
             //3->（解析）：正在解析响应内容。
             //4->（完成）：响应内容解析完成，可以在客户端调用。
             if(oAjax.readyState==4)
             {
                   if(oAjax.status==200)//判断是否成功,如果是200，就代表成功
                   {
                         alert("成功"+oAjax.responseText);//读取a.txt文件成功就弹出成功。后面加上oAjax.responseText会输出a.txt文本的内容
                   }
                   else
                   {
                         alert("失败");
                   }
             }
         };
    }
</script>
</div>
{% endblock %}