article/urls.py
from django.urls import path
from article.views import aindex,detail,setRate,search,doExcelIndex,getNews
app_name = 'article'
urlpatterns = [
	path('aindex/', aindex,name='aindex'),
    path('detail/', detail,name="detail"),
    path('setRate/', setRate,name="setRate"),
    path('search/', search,name="search"),
    path('doExcelIndex/',doExcelIndex, name= "doExcelIndex"),
    path('getNews/',getNews,name = "getNews")
]

map/urls.py
from django.urls import path
from map.views import index
app_name = 'map'
urlpatterns = [
	path('map_index/', index,name='map_index'),
]

xwproj/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

article/models.py
from django.db import models

# Create your models here.

article/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,JsonResponse
import json
import requests
from django.db import connection
from bs4 import BeautifulSoup as bs
from urllib.parse import quote
# Create your views here.

def aindex(request):
    #page = request.GET.get("page")
    #pSize = request.GET.get("pageSize")
    response = {}
    total =  0
    with connection.cursor() as cur:
        cur.execute("select count(1) from spider.com_news")
        total = cur.fetchall()[0][0]
    response["total"] = total
    response["data"] = []
    with connection.cursor() as cur:
        cur.execute("select title,entityurl,entitytime,rate from spider.com_news where rate is null order by entitytime desc limit 50")
        data = cur.fetchall()
    response["data"] = [{"title":x,"entityurl":y,"entitytime":z,"rate":k} for x,y,z,k in data]
    return render(request,"article/index.html",response)

def detail(request):
    url = request.GET.get("entityurl")
    title = request.GET.get("title")
    rate = request.GET.get("rate")
    return render(request,"article/detail.html",{"title":title,"entityurl":url,"rate":rate})

def setRate(request):
    entityurl = request.POST.get("entityurl")
    rate = request.POST.get("rate")
    with connection.cursor() as cur:
        cur.execute("update spider.com_news set rate = '{0}',ready=1 where entityurl = '{1}'".format(rate,entityurl))
    return JsonResponse({"status":'success'})

def search(request):
    response = {}
    ifcate = request.POST.get("ifcate")
    main_key = request.POST.get("main_key")
    cate = 0
    if ifcate in ["cate","nocate"]:
        with connection.cursor() as cur:
            cur.execute("select title,entityurl,entitytime,rate from spider.com_news where ready={0} and data_source is null order by data_source asc limit 100".format(1 if ifcate=="cate" else 0))
            data = cur.fetchall()
    elif ifcate!="train":
        with connection.cursor() as cur:
            cur.execute("select title,entityurl,entitytime,rate from spider.com_news where title like '%%{0}%%'".format(main_key))
            data = cur.fetchall()
    else:
        c = "C1,C2,C3,C4,C6,C8,C3_tt,Other,risk,instInfo"
        cate=1
        with connection.cursor() as cur:
            cur.execute("select {0} from com_news_train".format(c))
            data = cur.fetchall()
    if cate ==0:
        response["data"] = [{"title":x,"entityurl":y,"entitytime":z,"rate":k} for x,y,z,k in data]
        return render(request,"article/lists.html",response)
    else:
        cList = c.split(",")
        response["data"] =  [{cList[0]:x0,cList[1]:x1,cList[2]:x2,cList[3]:x3,cList[4]:x4,cList[5]:x5,cList[6]:x6,cList[7]:x7,cList[8]:x8,cList[9]:x9} for x0,x1,x2,x3,x4,x5,x6,x7,x8,x9 in data]
        return render(request,"article/lists_train.html",response)

def doExcelIndex(request):
    return render(request,"article/excelindex.html")

def getNews(request):
    content = request.FILES.get('myexcel').read()
    soup = bs(content,"lxml")
    trs = soup.find("table").find_all("tr")
    for tr in trs:
        name = tr.find_all("td")[1].text
        rate = tr.find_all("td")[3].find("span").text
        getUrl(name,rate)
    return redirect("http://39.97.184.89:5050/articleaindex/")

def getUrl(name,rate):
    headers = {
        "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36",
    }
    s = requests.session()
    s.get("https://www.baidu.com/",headers=headers)
    url = """https://www.baidu.com/s?wd={0}""".format(quote(name,'utf-8'))
    entityurl = None
    try:
        resp = s.get(url,headers= headers)
        resp.encoding = "utf8"
        soup = bs(resp.text,"lxml")
        content = soup.find_all("div",attrs={"id":"content_left"})[0]
        lists = content.find_all("div",attrs={"class":"result c-container"})
        for li in lists:
            aa = li.find_all("a")
            for tt in aa:
                if name in tt.text:
                    entityurl = tt.get("gref")
                    break
        if entityurl == None:
            entityurl = lists[0].find_all("a")[0].get("href")
    except:
        pass
    finally:
        if entityurl!=None:
            with connection.cursor() as cur:
                cur.execute("select title from com_news where title='{0}'".format(name))
                result = cur.fetchone()
                if result == None:
                    print(name)
                    cur.execute("insert into com_news(title,entityurl,rate,ready) values('%s','%s','%s',0)" %(name,entityurl,rate))
                    connection.commit()

templates/article/detail.html
{% extends "base.html" %}
{% block title %}守正评级数据仓库{% endblock %}
{% block content %}
<div class="row">
<div class="col-md-2"></div>
<div class="col-md-8">
    <h2>{{ title }}</h2>
    <div style="margin-top:10px;margin-bottom:10px" align="right">
        <label>大智慧分类为:<em>{{ rate }}</em></label>
        <select name="rate" onchange="rate()">
        <option select="selected">请选择类别</option>
        <option value="正向">正向</option>
        <option value="中立">中立</option>
        <option value="负向一星">负向一星</option>
        <option value="负向二星">负向二星</option>
        <option value="负向三星">负向三星</option>
        <option value="不评价">不评价</option>
        </select>
    </div>
    
    <div>
        <iframe src="{{ entityurl }}" style="width:100%;min-height:700px">
    
        </iframe>
    </div>
</div>
<div class = "col-md-2"></div>
</div>
<script language="JavaScript">
    function rate(){
        var form = new FormData();
        var mType = document.getElementsByName("rate")[0];
        var val = mType.value;
        form.append("csrfmiddlewaretoken",'{{ csrf_token }}');
        form.append("entityurl",'{{ entityurl }}');
        form.append("rate",val);
        var xmlHttp = new XMLHttpRequest();
        xmlHttp.onreadystatechange = function()
        {
             if (xmlHttp.readyState == 4 && xmlHttp.status == 200) {
                alert("您已为该条咨询评为:"+val)
             }
        }
        xmlHttp.open("POST", "{% url 'article:setRate' %}", false);
        xmlHttp.send(form);
    }
</script>
{% endblock %}

templates/article/excelindex.html
{% extends "base.html" %}
{% block title %}守正评级数据仓库{% endblock %}
{% block content %}
<div class="row">
<div class="col-md-2"></div>
<div class="col-md-8">
    <form action="{% url 'article:getNews' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-group">
          <label for="exampleInputFile">请上传从大智慧365下载的excel</label>
          <input type="file" id="myexcel" name = "myexcel">
          <p class="help-block">Example block-level help text here.</p>
      </div>

      <button type="submit" class="btn btn-default">提交</button>
   </form>
</div>
<div class="col-md-2"></div>
</div>
{% endblock %}

templates/article/index.html
{% extends "base.html" %}
{% block title %}守正评级数据仓库{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
    <form class="navbar-form navbar-left" action = "{% url 'article:search' %}" method='post'>
        {% csrf_token %}
        <div class="form-group">
            <select class="form-control" name = "ifcate">
                <option value=0>请选择有无分类</option>
                <option value = "cate">已分类</option>
                <option value="nocate">未分类</option>
                <!--<option value="train">大智慧365训练样本</option>-->
            </select>
        </div>
        <div class="form-group">
             <input type="text" name="main_key" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
    <div><a href="{% url 'article:doExcelIndex' %}">上传大智慧365负面新闻Excel</a></div>
    </div>
    <div class="col-md-2"></div>
</div>
<div class="row">
<div class="col-md-2"></div>
<div class="col-md-8">
    <table class = "table">
        {% block newslist %}

        <thead>
            <th>标题</th>
            <th>正文链接</th>
            <th>时间</th>
            <th>分类</th>
        <thead>
        <tbody>
            {% for line in data %}
                <tr>
                    <td><a href="/articledetail?entityurl={{ line.entityurl }}&title={{ line.title }}&rate={{ line.rate }}">{{ line.title }}</a></td>
                    <td>{{ line.entityurl }} </td>
                    <td>{{ line.entitytime }} </td>
                    <td>{{ line.rate }}</td>
                </tr>
            {% endfor %}
            {% endblock %}
        <tbody>
    </table>
</div>
<div class = "col-md-2"></div>
</div>
{% endblock %}

templates/article/lists.html
{% extends 'article/index.html' %}

{% block newslist %}
<thead>
            <th>标题</th>
            <th>正文链接</th>
            <th>时间</th>
            <th>分类</th>
<thead>
<tbody>

    {% for line in data %}
        <tr>
            <td><a href="/articledetail?entityurl={{ line.entityurl }}&title={{ line.title }}&rate={{ line.rate }}">{{ line.title }}</a></td>
            <td>{{ line.entityurl }} </td>
            <td>{{ line.entitytime }} </td>
            <td>{{ line.rate }}</td>
        </tr>
    {% endfor %}
{% endblock %}

templates/article/lists_train.html
{% extends 'article/index.html' %}

{% block newslist %}
<thead>
 <th>C1</th>
 <th>C2</th>
 <th>C3</th>
 <th width="50px">C4</th>
 <th>C6</th>
 <th>C8</th>
 <th>C3_tt</th>
 <th>Other</th>
 <th>risk</th>
 <th>instInfo</th>
<thead>
<tbody>

    {% for line in data %}
        <tr>
            <td>{{ line.C1 }}</td>
            <td>{{ line.C2 }} </td>
            <td>{{ line.C3 }} </td>
            <td width='2%'>{{ line.C4 }}</td>
            <td>{{ line.C6 }}</td>
            <td>{{ line.C8 }}</td>
            <td>{{ line.C3_tt }}</td>
            <td>{{ line.Other }}</td>
            <td>{{ line.risk }}</td>
            <td>{{ line.instInfo }}</td>
        </tr>
    {% endfor %}
{% endblock %}